services:
    daf.real_db_connection.main:
        class:            Doctrine\DBAL\Driver\Connection
        factory:          ["@doctrine.dbal.main_connection", getWrappedConnection]

#    example:
#        class: Path\To\Class
#        arguments: [@service, %parameter%]
#        tags:
#            -  { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
